-- SUPABASE SCHEMA AND SECURITY POLICIES FOR RAPHA CARES
-- You can run this script directly in the Supabase SQL Editor

-- 1. Create Providers Table (Therapists and Psychiatrists)
CREATE TABLE IF NOT EXISTS public.providers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    role text NOT NULL, -- 'Therapist' or 'Psychiatrist'
    credentials text,
    location text,
    focus text,
    price text,
    bio text,
    calendly text,
    image_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Resources Table
CREATE TABLE IF NOT EXISTS public.resources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    author text,
    note text,
    category text NOT NULL, -- 'Books', 'Sermons', 'Music', etc.
    link_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Team Members Table
CREATE TABLE IF NOT EXISTS public.team_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    title text NOT NULL,
    bio text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Prayer Requests Table
CREATE TABLE IF NOT EXISTS public.prayer_requests (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prayer_requests ENABLE ROW LEVEL SECURITY;

-- 5. Define Row Level Security Policies

-- Providers Policies
CREATE POLICY "Allow public read of providers" ON public.providers
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write of providers" ON public.providers
    FOR ALL TO authenticated
    USING (auth.jwt() ->> 'email' = 'weareraphacares@gmail.com')
    WITH CHECK (auth.jwt() ->> 'email' = 'weareraphacares@gmail.com');

-- Resources Policies
CREATE POLICY "Allow public read of resources" ON public.resources
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write of resources" ON public.resources
    FOR ALL TO authenticated
    USING (auth.jwt() ->> 'email' = 'weareraphacares@gmail.com')
    WITH CHECK (auth.jwt() ->> 'email' = 'weareraphacares@gmail.com');

-- Team Members Policies
CREATE POLICY "Allow public read of team_members" ON public.team_members
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write of team_members" ON public.team_members
    FOR ALL TO authenticated
    USING (auth.jwt() ->> 'email' = 'weareraphacares@gmail.com')
    WITH CHECK (auth.jwt() ->> 'email' = 'weareraphacares@gmail.com');

-- Prayer Requests Policies
CREATE POLICY "Allow public insert of prayer_requests" ON public.prayer_requests
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow admin view and delete of prayer_requests" ON public.prayer_requests
    FOR ALL TO authenticated
    USING (auth.jwt() ->> 'email' = 'weareraphacares@gmail.com')
    WITH CHECK (auth.jwt() ->> 'email' = 'weareraphacares@gmail.com');
